name: Run tests

permissions:
  contents: read

on:
  push:
     branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-24.04
 
    env:
      KAFNUS_TESTS_USE_EXTERNAL_POSTGIS: "false"
      KAFNUS_TESTS_E2E_MANUAL_INSPECTION: "false"
      KAFNUS_TESTS_LOG_LEVEL: DEBUG
      KAFNUS_DBPATH_POSTGIS: /data/postgis
      KAFNUS_POSTGIS_IMAGE: postgis/postgis:15-3.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('tests/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: tests
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Ensure kafka-postgis-net exists
        run: |
          if ! docker network ls | grep -q kafka-postgis-net; then
            docker network create kafka-postgis-net
          fi
      
      - name: Setup PostGIS data directory
        run: |
          sudo mkdir -p /data/postgis
          sudo chown -R 999:999 /data/postgis

      - name: Pre-pull required docker images
        run: |
          docker pull postgis/postgis:15-3.3
          docker pull apache/kafka:4.1.0
          docker pull mongo:8.0

      - name: Build kafnus-connect image
        working-directory: .
        run: |
          docker build --no-cache -t kafnus-connect .
    
      - name: Run with pytest
        working-directory: tests
        run: |
          source .venv/bin/activate
          pytest -s test_pipeline.py
